##############################################################
# Original Author: Hank Preston <hapresto@cisco.com>
# Modified by: Maksim Nikiforov <maksim@redhat.com>
##############################################################
---
- name: Example 2 - Managing Application Profiles and EPGs
  hosts: apic
  connection: local
  gather_facts: False
  vars:
    tenant: "{{ prefix }}_Tenant2"
    ap: "Supply_Chain"
    epgs:
      - epg: "web"
      - epg: "sql"

  tasks:
    - name: Create Application Profile
      aci_ap:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"
        descr: "App Profile Created Using Ansible"

    - name: Create EPGs
      aci_epg:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"
        epg: "{{ item.epg }}"
        description: "EPG Created Using Ansible"
      with_items: "{{ epgs }}"