##############################################################
# Original Author: Hank Preston <hapresto@cisco.com>
# Modified by: Maksim Nikiforov <maksim@redhat.com>
##############################################################
---
- name: Create Application(s)
  hosts: apic
  connection: local
  gather_facts: False
  vars_files:
    - vars/tenant_vars.yml

  tasks:
    - name: Wofklow Task 10 - Ensure Application Exists
      aci_ap:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"
        descr: "App Profile Created Using Ansible"

