- hosts: cisco
  gather_facts: no
  connection: network_cli
  tasks:
    - include_role:
        name: network-backup
      vars:
        network_backup_repository: 'git@github.com:scimaksim/network_programmability.git'

