---
- name: Enable Arista eAPI
  connection: network_cli
  gather_facts: false
  become: yes
  hosts: eos

  tasks:

  - name: Enable eAPI with no HTTP, HTTPS at port 9443, local HTTP at port 80, and socket enabled
    eos_eapi:
      state: started
      http: true
      https: no
      local_http: no
      socket: no