---
- name: Enable Arista eAPI
  connection: network_cli
  gather_facts: false
  hosts: all

  tasks:

  - name: Enable eAPI with no HTTP, HTTPS at port 9443, local HTTP at port 80, and socket enabled
    eos_eapi:
      state: started
      http: false
      https_port: 9443
      local_http: yes
      local_http_port: 80
      socket: yes