plugin: netbox
api_endpoint: http://192.168.122.176:8000
validate_certs: False
config_context: False

# Query filters are passed directly as an argument to the fetching queries.
# You can repeat tags in the query string.

# See the NetBox documentation at https://netbox.readthedocs.io/en/latest/api/overview/
# the query_filters work as a logical **OR**
#
# Prefix any custom fields with cf_ and pass the field value with the regular NetBox query string


# NetBox inventory plugin also supports Constructable semantics
# You can fill your hosts vars using the compose option:

