######
#For RPM-based distributions (e.g. RHEL, Fedora)
#This playbooks retrieves and installs GNS3 and its dependencies
#https://www.gns3.com/
######
- hosts: localhost
  become: yes
  gather_facts: no

  tasks:
    - name: Install platform-python-devel (a dependency)
      yum:
        name: platform-python-devel
        state: present
    
    - name: Install python3-pyqt5-sip (a dependency)
      yum:
        name: python3-pyqt5-sip
        state: present
    
    - name: Install python3-qt5 (a dependency)
      yum:
        name: python3-qt5
        state: present
    
    - name: Install gns3-server using pip
      pip:
        name: gns3-server
        state: latest
    
    - name: Install gns3-gui using pip
      pip:
        name: gns3-gui
        state: latest