######
#For RPM-based distributions (e.g. RHEL, Fedora)
#This playbooks retrieves and installs the MG-SOFT YANG Explorer Professional Edition 
#https://www.mg-soft.si/mgYangExplorer.html
######
- hosts: localhost
  become: yes
  gather_facts: no

  tasks:
    - name: Download YANG Explorer Professional Edition from MG-SOFT 
      get_url:
        url: https://www1.mg-soft.com/files/mgYangExplorer-2019a-rpm.tar.gz
        dest: /tmp
    
    - name: Extract the contents of the downloaded archive
      unarchive: 
        src: /tmp/mgYangExplorer-2019a-rpm.tar.gz
        dest: /tmp/

    - name: Ensure OpenJDK is present
      yum: 
        name: java-11-openjdk
        state: present

    - name: Install the extracted RPM
      yum:
        name: /tmp/mgYangExplorer-2019a-rpm/mgYangExplorer_2019-5.1-1.x86_64.rpm
        state: present
    
