##############################################################
# Original Author: Hank Preston <hapresto@cisco.com>
# Modified by: Maksim Nikiforov <maksim@redhat.com>
##############################################################
---
- name: Create Contracts Within EPGs
  hosts: apic
  connection: local
  gather_facts: False
  vars_files:
    - vars/tenant_vars.yml

  tasks:
    - name: Workflow Task 13 - Ensure EPGs Have Contracts
      aci_epg_to_contract:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"
        epg: "{{ item.epg }}"
        contract: "{{ item.contract }}"
        contract_type: "{{ item.contract_type }}"
      with_items: "{{ epg_contracts }}"

