##############################################################
# Original Author: Hank Preston <hapresto@cisco.com>
# Modified by: Maksim Nikiforov <maksim@redhat.com>
##############################################################
---
- name: Create Tenant Filters
  hosts: apic
  connection: local
  gather_facts: False
  vars_files:
    - vars/tenant_vars.yml

  tasks:
    - name: Workflow Task 05 - Ensure Tenant Filters Exist
      aci_filter:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ tenant }}"
        filter: "{{ item.filter }}"
        descr: "Filter Created Using Ansible"
      with_items: "{{ filters }}"

