##############################################################
# Original Author: Hank Preston <hapresto@cisco.com>
# Modified by: Maksim Nikiforov <maksim@redhat.com>
##############################################################
---
- name: Bind Domain to EPG
  hosts: apic
  connection: local
  gather_facts: False
  vars_files:
    - vars/tenant_vars.yml

  tasks:
    - name: Workflow Task 12 - Ensure Domain Is Bound To EPG
      aci_epg_to_domain:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"
        epg: "{{ item.epg }}"
        domain: "aci_ansible_lab"
        domain_type: "vmm"
        vm_provider: "vmware"
        encap_mode: "auto"
        encap: "{{ item.encap }}"
      with_items: "{{ epgs }}"

